"""Create vehicles & vehicle_positions tables

Revision ID: 7076062a2ab9
Revises: 
Create Date: 2025-04-29 11:55:10.699738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7076062a2ab9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vehicles',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('trip_id', sa.String(), nullable=False),
        sa.Column('line_product', sa.Enum('BUS', 'SUBWAY', 'TRAMWAY', 'SUBURBAN', 'FERRY', 'EXPRESS', 'REGIONAL', name='line_product_enum'), nullable=False),
        sa.Column('line_name', sa.String(), nullable=False),
        sa.Column('partition_dt', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        postgresql_partition_by='RANGE (partition_dt)'
    )
    op.create_table(
        'vehicle_positions',
        sa.Column('vehicle_id', sa.UUID(), nullable=False),
        sa.Column('timestamp', postgresql.TIMESTAMP(), nullable=False),
        sa.Column('latitude', sa.DECIMAL(precision=38, scale=18), nullable=False),
        sa.Column('longitude', sa.DECIMAL(precision=38, scale=18), nullable=False),
        sa.Column('partition_dt', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('vehicle_id', 'timestamp'),
        postgresql_partition_by='RANGE (partition_dt)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_positions')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
